// package io.alauda.jenkins.devops.sync.action;
//
// import com.gargoylesoftware.htmlunit.Page;
// import com.gargoylesoftware.htmlunit.WebResponse;
// import io.alauda.jenkins.devops.sync.JenkinsK8sRule;
// import io.alauda.jenkins.devops.sync.WithoutK8s;
// import net.sf.json.JSONObject;
// import org.junit.Rule;
// import org.junit.Test;
// import org.jvnet.hudson.test.JenkinsRule;
// import org.jvnet.hudson.test.WithoutJenkins;
// import org.xml.sax.SAXException;
//
// import java.io.IOException;
// import java.util.Locale;
//
// import static org.hamcrest.Matchers.anyOf;
// import static org.hamcrest.Matchers.equalTo;
// import static org.junit.Assert.*;
//
// public class KubernetesClientActionTest {
//    @Rule
//    public JenkinsK8sRule j = new JenkinsK8sRule();
//
//    @Test
//    public void doConnectTest() throws IOException, SAXException {
//        JenkinsRule.WebClient wc = j.createWebClient();
//
//        wc.getOptions().setThrowExceptionOnFailingStatusCode(false);
//
//        {
//            // valid check
//            Page page = wc.goTo("alauda/connectTest", null);
//            WebResponse response = page.getWebResponse();
//            assertEquals(200, response.getStatusCode());
//
//            String text = response.getContentAsString();
//            JSONObject json = JSONObject.fromObject(text);
//
//            assertEquals(json.get("status").toString(), "ok");
//            assertTrue("kubernetes connect error",
//                    json.getJSONObject("data").getBoolean("success"));
//        }
//
//        {
//            // invalid check
//            Page page = wc.goTo("alauda/connectTest?server=a&credentialId=a", null);
//            WebResponse response = page.getWebResponse();
//            assertEquals(200, response.getStatusCode());
//
//            String text = response.getContentAsString();
//            JSONObject json = JSONObject.fromObject(text);
//
//            assertEquals(json.get("status").toString(), "ok");
//            assertFalse("kubernetes connect error",
//                    json.getJSONObject("data").getBoolean("success"));
//        }
//    }
//
//    @Test
//    @WithoutK8s
//    public void doBuildId() throws IOException, SAXException {
//        JenkinsRule.WebClient wc = j.createWebClient();
//        wc.getOptions().setThrowExceptionOnFailingStatusCode(false);
//
//        Page page = wc.goTo("alauda/buildId", "application/json");
//        WebResponse response = page.getWebResponse();
//        assertEquals(200, response.getStatusCode());
//
//        String text = response.getContentAsString();
//        JSONObject json = JSONObject.fromObject(text);
//
//        // debug file should generated by ci
//        assertThat(json.get("status").toString(), anyOf(equalTo("error"),
//                equalTo("ok")));
//
//    }
//
//    @Test
//    @WithoutK8s
//    public void doCronTabCheck() throws IOException, SAXException {
//        JenkinsRule.WebClient wc = j.createWebClient();
//        wc.getOptions().setThrowExceptionOnFailingStatusCode(false);
//        String correctCron = "* * * * *";
//
//        Page page = wc.goTo("alauda/cronTabCheck?cronText=" + correctCron,
//                "application/json");
//        WebResponse response = page.getWebResponse();
//        assertEquals(200, response.getStatusCode());
//
//        String text = response.getContentAsString();
//        JSONObject json = JSONObject.fromObject(text);
//
//        assertNotNull(json.getJSONObject("data").get("next"));
//        assertNotNull(json.getJSONObject("data").get("previous"));
//        assertNotNull(json.getJSONObject("data").get("sanity_" + Locale.SIMPLIFIED_CHINESE));
//        assertNotNull(json.getJSONObject("data").get("sanity_" + Locale.ENGLISH));
//    }
// }
